export const BASE_TAGS: Record<string, string> = {
  rpg: "RPG",
  "open-world": "Open World",
  "story-rich": "Story Rich",
  exploration: "Exploration",
  fantasy: "Fantasy",
  "sci-fi": "Sci-Fi",
  horror: "Horror",
  survival: "Survival",
  shooter: "Shooter",
  platformer: "Platformer",
  strategy: "Strategy",
  puzzle: "Puzzle",
  racing: "Racing",
  management: "Management",
  crafting: "Crafting",
  building: "Building",
  roguelike: "Roguelike",
  medieval: "Medieval",
  cyberpunk: "Cyberpunk",
  "post-apocalyptic": "Post-Apocalyptic",
};
