export const TAG_DISPLAY_NAMES: Record<string, string> = {
  // Core modes and genres
  "auto-battler": "Auto Battler",
  "board-game": "Board Game",
  "card-game": "Card Game",
  "co-op": "Co-op",
  "dating-sim": "Dating Sim",
  "deck-builder": "Deck Builder",
  deckbuilding: "Deckbuilding",
  "endless-runner": "Endless Runner",
  fighting: "Fighting",
  fps: "FPS",
  idle: "Idle",
  "local-multiplayer": "Local Multiplayer",
  management: "Management",
  metroidvania: "Metroidvania",
  mmo: "MMO",
  moba: "MOBA",
  multiplayer: "Multiplayer",
  platformer: "Platformer",
  "point-and-click": "Point & Click",
  puzzle: "Puzzle",
  racing: "Racing",
  roguelike: "Roguelike",
  roguelite: "Roguelite",
  rpg: "RPG",
  rts: "RTS",
  runner: "Endless Runner",
  shooter: "Shooter",
  simulation: "Simulation",
  singleplayer: "Singleplayer",
  soulslike: "Soulslike",
  strategy: "Strategy",
  "tower-defense": "Tower Defense",
  "turn-based": "Turn-Based",
  "visual-novel": "Visual Novel",

  // Perspective, presentation, and style
  "2.5d": "2.5D",
  "2d": "2D",
  "3d": "3D",
  anime: "Anime",
  cartoony: "Cartoony",
  cinematic: "Cinematic",
  colorful: "Colorful",
  "comic-book": "Comic Book",
  "first-person": "First Person",
  "hand-drawn": "Hand-Drawn",
  isometric: "Isometric",
  minimalist: "Minimalist",
  noir: "Noir",
  "pixel-art-game": "Pixel Art",
  "pixel-graphics": "Pixel Art",
  retro: "Retro",
  stylized: "Stylized",
  surrealism: "Surreal",
  "third-person": "Third Person",
  "top-down": "Top-Down",
  voxel: "Voxel",

  // World, setting, and themes
  "cold-war": "Cold War",
  cyberpunk: "Cyberpunk",
  "dark-fantasy": "Dark Fantasy",
  demons: "Demons",
  dinosaurs: "Dinosaurs",
  dragons: "Dragons",
  "dungeons-dragons": "Dungeons & Dragons",
  fantasy: "Fantasy",
  historical: "Historical",
  japanese: "Japanese",
  lovecraft: "Lovecraftian",
  military: "Military",
  mythology: "Mythology",
  "open-world": "Open World",
  pirates: "Pirates",
  "post-apocalyptic": "Post-Apocalyptic",
  robots: "Robots",
  "sci-fi": "Sci-Fi",
  "science-fantasy": "Science Fantasy",
  "science-fiction": "Sci-Fi",
  space: "Space",
  war: "War",
  "world-war-2": "World War II",
  "world-war-i": "World War I",
  zombies: "Zombies",

  // Gameplay mechanics and systems
  action: "Action",
  "action-adventure": "Action-Adventure",
  adventure: "Adventure",
  archery: "Archery",
  "base-building": "Base Building",
  "battle-royale": "Battle Royale",
  "beat-em-up": "Beat ",
  "bullet-hell": "Bullet Hell",
  "bullet-time": "Bullet Time",
  "class-based": "Class-Based",
  crafting: "Crafting",
  difficult: "Difficult",
  economy: "Economy",
  exploration: "Exploration",
  farming: "Farming",
  "grappling-hook": "Grappling Hook",
  "grid-based": "Grid-Based",
  "hack-and-slash": "Hack and Slash",
  "hex-grid": "Hex Grid",
  loot: "Loot",
  melee: "Melee Combat",
  physics: "Physics-Based",
  procedural: "Procedural",
  "procedural-generation": "Procedural Generation",
  "quick-time-events": "Quick-Time Events",
  "resource-management": "Resource Management",
  "score-attack": "Score Attack",
  speedrun: "Speedrun",
  stealth: "Stealth",
  survival: "Survival",
  "team-based": "Team-Based",
  "time-manipulation": "Time Manipulation",
  "time-pressure": "Time Pressure",
  "time-trial": "Time Trial",
  "trading-card-game": "Trading Card Game",
  "turn-based-combat": "Turn-Based Combat",
  "vehicle-combat": "Vehicular Combat",
  "wall-jumping": "Wall Jumping",
  "wall-running": "Wall Running",

  // Narrative and character
  "based-on-a-novel": "Based on a Novel",
  choices: "Choices Matter",
  "choices-matter": "Choices Matter",
  "choose-your-own-adventure": "Choose Your Own Adventure",
  comedy: "Comedy",
  "coming-of-age": "Coming of Age",
  conversation: "Conversation",
  crime: "Crime",
  "dark-humor": "Dark Humor",
  detective: "Detective",
  emotional: "Emotional",
  episodic: "Episodic",
  "female-protagonist": "Female Protagonist",
  heist: "Heist",
  "multiple-endings": "Multiple Endings",
  mystery: "Mystery",
  narration: "Narration",
  romance: "Romance",
  "silent-protagonist": "Silent Protagonist",
  story: "Story Rich",
  "story-rich": "Story Rich",
  "villain-protagonist": "Villain Protagonist",

  // Mood, audience, and content
  atmospheric: "Atmospheric",
  casual: "Casual",
  chill: "Chill",
  cozy: "Cozy",
  cute: "Cute",
  dark: "Dark",
  dreamlike: "Dreamlike",
  educational: "Educational",
  "free-to-play": "Free to Play",
  funny: "Funny",
  horror: "Horror",
  "lgbtq-2": "LGBTQ+",
  mature: "Mature",
  psychological: "Psychological",
  relaxing: "Relaxing",
  remake: "Remake",

  // Audio, sports, and misc
  esports: "Esports",
  football: "Football",
  "hip-hop": "Hip-Hop",
  indie: "Indie",
  magic: "Magic",
  match: "Match",
  monsters: "Monsters",
  music: "Music / Rhythm",
  ninja: "Ninja",
  photography: "Photography",
  rhythm: "Rhythm",
  sandbox: "Sandbox",
  science: "Science",
  underwater: "Underwater",
  vr: "VR",

  // Other display names
  "alternate-history": "Alternate History",
  "augmented-reality": "AR",
  "boss-battles": "Boss Battles",
  combat: "Combat",
  "dungeon-crawler": "Dungeon Crawler",
  dystopian: "Dystopian",
  "escape-room": "Escape Room",
  "fast-paced": "Fast-Paced",
  "horror-games": "Horror",
  "immersive-sim": "Immersive Sim",
  linear: "Linear",
  mmorpg: "MMORPG",
  nonlinear: "Nonlinear",
  parkour: "Parkour",
  "puzzle-platformer": "Puzzle-Platformer",
  "side-scroller": "Side Scroller",
  synthwave: "Synthwave",
  "time-travel": "Time Travel",
  "walking-sim": "Walking Simulator",
  "walking-simulator": "Walking Simulator",
};
